    { lang_e::AB, "AB", "ab", "abk", "Abkhaz" },
    { lang_e::AA, "AA", "aa", "aar", "Afar" },
    { lang_e::AF, "AF", "af", "afr", "Afrikaans" },
    { lang_e::AK, "AK", "ak", "aka", "Akan" },
    { lang_e::SQ, "SQ", "sq", "sqi", "Albanian" },
    { lang_e::AM, "AM", "am", "amh", "Amharic" },
    { lang_e::AR, "AR", "ar", "ara", "Arabic" },
    { lang_e::AN, "AN", "an", "arg", "Aragonese" },
    { lang_e::HY, "HY", "hy", "hye", "Armenian" },
    { lang_e::AS, "AS", "as", "asm", "Assamese" },
    { lang_e::AV, "AV", "av", "ava", "Avaric" },
    { lang_e::AZ, "AZ", "az", "aze", "Azerbaijani" },
    { lang_e::BM, "BM", "bm", "bam", "Bambara" },
    { lang_e::BA, "BA", "ba", "bak", "Bashkir" },
    { lang_e::BE, "BE", "be", "bel", "Belarusian" },
    { lang_e::BN, "BN", "bn", "ben", "Bengali, Bangla" },
    { lang_e::BH, "BH", "bh", "bih", "Bihari" },
    { lang_e::BI, "BI", "bi", "bis", "Bislama" },
    { lang_e::BS, "BS", "bs", "bos", "Bosnian" },
    { lang_e::BR, "BR", "br", "bre", "Breton" },
    { lang_e::BG, "BG", "bg", "bul", "Bulgarian" },
    { lang_e::MY, "MY", "my", "mya", "Burmese" },
    { lang_e::CA, "CA", "ca", "cat", "Catalan" },
    { lang_e::CH, "CH", "ch", "cha", "Chamorro" },
    { lang_e::CE, "CE", "ce", "che", "Chechen" },
    { lang_e::NY, "NY", "ny", "nya", "Chichewa, Chewa, Nyanja" },
    { lang_e::ZH, "ZH", "zh", "zho", "Chinese" },
    { lang_e::CV, "CV", "cv", "chv", "Chuvash" },
    { lang_e::KW, "KW", "kw", "cor", "Cornish" },
    { lang_e::CO, "CO", "co", "cos", "Corsican" },
    { lang_e::CR, "CR", "cr", "cre", "Cree" },
    { lang_e::HR, "HR", "hr", "hrv", "Croatian" },
    { lang_e::CS, "CS", "cs", "ces", "Czech" },
    { lang_e::DA, "DA", "da", "dan", "Danish" },
    { lang_e::DV, "DV", "dv", "div", "Divehi, Dhivehi, Maldivian" },
    { lang_e::NL, "NL", "nl", "nld", "Dutch" },
    { lang_e::DZ, "DZ", "dz", "dzo", "Dzongkha" },
    { lang_e::EN, "EN", "en", "eng", "English" },
    { lang_e::ET, "ET", "et", "est", "Estonian" },
    { lang_e::EE, "EE", "ee", "ewe", "Ewe" },
    { lang_e::FO, "FO", "fo", "fao", "Faroese" },
    { lang_e::FJ, "FJ", "fj", "fij", "Fijian" },
    { lang_e::FI, "FI", "fi", "fin", "Finnish" },
    { lang_e::FR, "FR", "fr", "fra", "French" },
    { lang_e::FF, "FF", "ff", "ful", "Fula, Fulah, Pulaar, Pular" },
    { lang_e::GL, "GL", "gl", "glg", "Galician" },
    { lang_e::KA, "KA", "ka", "kat", "Georgian" },
    { lang_e::DE, "DE", "de", "deu", "German" },
    { lang_e::EL, "EL", "el", "ell", "Greek (modern)" },
    { lang_e::GN, "GN", "gn", "grn", "Guaraní" },
    { lang_e::HT, "HT", "ht", "hat", "Haitian, Haitian Creole" },
    { lang_e::HZ, "HZ", "hz", "her", "Herero" },
    { lang_e::HO, "HO", "ho", "hmo", "Hiri Motu" },
    { lang_e::HU, "HU", "hu", "hun", "Hungarian" },
    { lang_e::ID, "ID", "id", "ind", "Indonesian" },
    { lang_e::GA, "GA", "ga", "gle", "Irish" },
    { lang_e::IG, "IG", "ig", "ibo", "Igbo" },
    { lang_e::IK, "IK", "ik", "ipk", "Inupiaq" },
    { lang_e::IO, "IO", "io", "ido", "Ido" },
    { lang_e::IS, "IS", "is", "isl", "Icelandic" },
    { lang_e::IT, "IT", "it", "ita", "Italian" },
    { lang_e::JV, "JV", "jv", "jav", "Javanese" },
    { lang_e::KL, "KL", "kl", "kal", "Kalaallisut, Greenlandic" },
    { lang_e::KN, "KN", "kn", "kan", "Kannada" },
    { lang_e::KR, "KR", "kr", "kau", "Kanuri" },
    { lang_e::KK, "KK", "kk", "kaz", "Kazakh" },
    { lang_e::KM, "KM", "km", "khm", "Khmer" },
    { lang_e::KI, "KI", "ki", "kik", "Kikuyu, Gikuyu" },
    { lang_e::KY, "KY", "ky", "kir", "Kyrgyz" },
    { lang_e::KV, "KV", "kv", "kom", "Komi" },
    { lang_e::KG, "KG", "kg", "kon", "Kongo" },
    { lang_e::LB, "LB", "lb", "ltz", "Luxembourgish, Letzeburgesch" },
    { lang_e::LG, "LG", "lg", "lug", "Ganda" },
    { lang_e::LI, "LI", "li", "lim", "Limburgish, Limburgan, Limburger" },
    { lang_e::LN, "LN", "ln", "lin", "Lingala" },
    { lang_e::LO, "LO", "lo", "lao", "Lao" },
    { lang_e::LT, "LT", "lt", "lit", "Lithuanian" },
    { lang_e::LUB, "LUB", "lub", "lub", "Luba-Katanga" },
    { lang_e::LV, "LV", "lv", "lav", "Latvian" },
    { lang_e::GV, "GV", "gv", "glv", "Manx" },
    { lang_e::MK, "MK", "mk", "mkd", "Macedonian" },
    { lang_e::MG, "MG", "mg", "mlg", "Malagasy" },
    { lang_e::ML, "ML", "ml", "mal", "Malayalam" },
    { lang_e::MT, "MT", "mt", "mlt", "Maltese" },
    { lang_e::MI, "MI", "mi", "mri", "Māori" },
    { lang_e::MH, "MH", "mh", "mah", "Marshallese" },
    { lang_e::MN, "MN", "mn", "mon", "Mongolian" },
    { lang_e::NA, "NA", "na", "nau", "Nauruan" },
    { lang_e::NV, "NV", "nv", "nav", "Navajo, Navaho" },
    { lang_e::ND, "ND", "nd", "nde", "Northern Ndebele" },
    { lang_e::NE, "NE", "ne", "nep", "Nepali" },
    { lang_e::NB, "NB", "nb", "nob", "Norwegian Bokmål" },
    { lang_e::NN, "NN", "nn", "nno", "Norwegian Nynorsk" },
    { lang_e::NO, "NO", "no", "nor", "Norwegian" },
    { lang_e::II, "II", "ii", "iii", "Nuosu" },
    { lang_e::NR, "NR", "nr", "nbl", "Southern Ndebele" },
    { lang_e::OC, "OC", "oc", "oci", "Occitan" },
    { lang_e::OJ, "OJ", "oj", "oji", "Ojibwe, Ojibwa" },
    { lang_e::OM, "OM", "om", "orm", "Oromo" },
    { lang_e::OR, "OR", "or", "ori", "Oriya" },
    { lang_e::OS, "OS", "os", "oss", "Ossetian, Ossetic" },
    { lang_e::PI, "PI", "pi", "pli", "Pāli" },
    { lang_e::PL, "PL", "pl", "pol", "Polish" },
    { lang_e::PT, "PT", "pt", "por", "Portuguese" },
    { lang_e::QU, "QU", "qu", "que", "Quechua" },
    { lang_e::RM, "RM", "rm", "roh", "Romansh" },
    { lang_e::RO, "RO", "ro", "ron", "Romanian" },
    { lang_e::RU, "RU", "ru", "rus", "Russian" },
    { lang_e::SC, "SC", "sc", "srd", "Sardinian" },
    { lang_e::SM, "SM", "sm", "smo", "Samoan" },
    { lang_e::SG, "SG", "sg", "sag", "Sango" },
    { lang_e::SR, "SR", "sr", "srp", "Serbian" },
    { lang_e::GD, "GD", "gd", "gla", "Scottish Gaelic, Gaelic" },
    { lang_e::SN, "SN", "sn", "sna", "Shona" },
    { lang_e::SI, "SI", "si", "sin", "Sinhalese, Sinhala" },
    { lang_e::SK, "SK", "sk", "slk", "Slovak" },
    { lang_e::SL, "SL", "sl", "slv", "Slovene" },
    { lang_e::SO, "SO", "so", "som", "Somali" },
    { lang_e::ST, "ST", "st", "sot", "Southern Sotho" },
    { lang_e::ES, "ES", "es", "spa", "Spanish" },
    { lang_e::SU, "SU", "su", "sun", "Sundanese" },
    { lang_e::SW, "SW", "sw", "swa", "Swahili" },
    { lang_e::SS, "SS", "ss", "ssw", "Swati" },
    { lang_e::SV, "SV", "sv", "swe", "Swedish" },
    { lang_e::TA, "TA", "ta", "tam", "Tamil" },
    { lang_e::TE, "TE", "te", "tel", "Telugu" },
    { lang_e::TH, "TH", "th", "tha", "Thai" },
    { lang_e::TI, "TI", "ti", "tir", "Tigrinya" },
    { lang_e::BO, "BO", "bo", "bod", "Tibetan Standard, Tibetan, Central" },
    { lang_e::TK, "TK", "tk", "tuk", "Turkmen" },
    { lang_e::TL, "TL", "tl", "tgl", "Tagalog" },
    { lang_e::TN, "TN", "tn", "tsn", "Tswana" },
    { lang_e::TO, "TO", "to", "ton", "Tonga (Tonga Islands)" },
    { lang_e::TR, "TR", "tr", "tur", "Turkish" },
    { lang_e::TS, "TS", "ts", "tso", "Tsonga" },
    { lang_e::TY, "TY", "ty", "tah", "Tahitian" },
    { lang_e::UK, "UK", "uk", "ukr", "Ukrainian" },
    { lang_e::VE, "VE", "ve", "ven", "Venda" },
    { lang_e::VI, "VI", "vi", "vie", "Vietnamese" },
    { lang_e::WA, "WA", "wa", "wln", "Walloon" },
    { lang_e::CY, "CY", "cy", "cym", "Welsh" },
    { lang_e::WO, "WO", "wo", "wol", "Wolof" },
    { lang_e::FY, "FY", "fy", "fry", "Western Frisian" },
    { lang_e::XH, "XH", "xh", "xho", "Xhosa" },
    { lang_e::YO, "YO", "yo", "yor", "Yoruba" },
    { lang_e::ZA, "ZA", "za", "zha", "Zhuang, Chuang" },
    { lang_e::ZU, "ZU", "zu", "zul", "Zulu" },
